### ISSUE TITLE
Issues with accessibility test

### ISSUE THREAD

**Issue by youbao88** [sassoftware/visual-analytics-sdk#35]
Hi there

When we are running the accessibility test, we got this feedback with some issues. 
[Accessibility Insights for Web automated checks result.pdf](https://github.com/sassoftware/visual-analytics-sdk/files/6121289/Accessibility.Insights.for.Web.automated.checks.result.pdf)

Thank you for your help!

**Comment by brmorr** [comment]
Hi @youbao88,

Sorry for the delay on this, as I am just seeing this issue.  Are you requiring some resolution on this?  Accessibility support is part of our priorities for the SDK.  I can certainly take this report and try to tease out any real issues and make sure we have internal issues created to resolve these.  Is that a reasonable resolution for you on this, or is there a need for these to be resolved in some specific time frame for you to generate a clean report?

**Comment by youbao88** [comment]
Hi 

Thank you so much for your replay. It's nice to know that accessibility support is with high priorities. Your resolution sounds like a good idea and ,from our side, we always prefer if you could solve this as soon as possible. 

Thank you again for your feedbacks on this.

**Comment by youbao88** [comment]
Hi @brmorr 

I noticed that you released a new version (0.16.0). I am wondering if those accessibility issues are fixed in this release. If it is not, is there any news on this issue? Thank you!

**Comment by brmorr** [comment]
It is not, as triage and prioritization of these fixes along side other work will take some time.

I have converted this to an internal issue, where we will triage the accessibility report errors and get individual issues created on the necessary front end components.  In order to clean up open issues I am going to mark this as resolved, but we can continue to communicate progress through this issue.

**Comment by sascds** [comment]
Hello @youbao88,

I'm the Director of Accessibility here at SAS. Thanks for your feedback on the VA SDK.  I would like to help.

First, I am blind. I cannot read the pdf you linked in because it is not accessible. Can you please export the test results from Accessibility Insights in HTML format and share them with me?

Second, I would like to understand the content you are building with the VA SDK. As you may know, VA and the VA SDK include many types of objects and capabilities. It would help us prioritize your request if you could share a screenshot and/or a description of the content you have built. Feel free to send email to accessibility@sas.com if you would prefer to share it offline.

Best,
Ed

**Comment by youbao88** [comment]
Hi developers

I am wondering is there any updates regarding this issue so far? Thank you!

Best regards,
Minhao Zhou

**Comment by brmorr** [comment]
Hi @youbao88,

We were able to recreate and fix the issues reported.  The fixes are currently being verified and should be available in the next version (v0.18.0) of the VASDK.
