### ISSUE TITLE
Too many redirects resulting in guest user not able to authenticate

### ISSUE THREAD

**Issue by YuryShkoda** [sassoftware/visual-analytics-sdk#84]
Hi there,
I'm using SAS VA SDK version `1.8.0` in order to embed VA report created on Viya `2021.2.5`.
Reference to VA SDK is in page head:
```html
<head>
    <meta charset="utf-8" />
    <link rel="icon" href="favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content=""
    />
    <link rel="apple-touch-icon" href="touch-icon-iphone-precomposed.png" />
    <link rel="manifest" href="manifest.json" />
    <title>App</title>
    <script async src="https://cdn.developer.sas.com/packages/va-report-components/latest/dist/umd/va-report-components.js"></script>
  </head>
```
Report tag:
```html
<sas-report
          authenticationType="guest"
          url="https://viya-url.com"
          reportUri="/reports/reports/a7d19a52-db06-4bef-a54c-8e5506b5db6e"
>
</sas-report>
```
Console screenshot:
![console](https://user-images.githubusercontent.com/25773492/170709838-1e93a7c8-560b-4fab-b8a1-59d39e650b00.png)
Network screenshot:
![network](https://user-images.githubusercontent.com/25773492/170710633-08340086-316b-4b80-ad0d-6a6e85b38480.png)

Thank you in advance.

**Comment by brmorr** [comment]
@YuryShkoda , if you go back to version 1.7.0, or even 1.6.0 of the SDK, do you see any different behavior?  I wouldn't expect you to, but this will help narrow down where the issue is.  Also, is this something you have had working before, with a different version of Viya, or is this a new setup?

Also, can you confirm that your Viya system is setup correctly for CORS, CSRF, and same-site cookie setting per https://developer.sas.com/sdk/va/docs/guides/viya-setup/.

**Comment by brmorr** [comment]
Also, if you can attache the HAR data that would help as well.  From the network tab in dev tools, right click and copy > copy all as har.  Then save to a file and attach to this issue.  Thanks!

**Comment by ckedwards** [comment]
Based off the attached image my best guess would be that the cookies do not have `samesite=none`.

If you look at the cookies tab for the requests like that authorize redirect, you should see the reponse setting a cookie. If that cookie does not have `samesite=none` then you may need to make that configuration change. If the configuration is set properly you may need to restart the services to see the change applied.
![Screen Shot 2022-05-27 at 3 36 34 PM](https://user-images.githubusercontent.com/279314/170779246-223c7899-c025-473e-b2e8-922516567730.png)

**Comment by YuryShkoda** [comment]
@ckedwards and @ckedwards, thanks for your responses. 
I've tried to roll back to version 1.6.0 and the behavior was the same.
I believe that I've configured CORS, CSRF and cookies properly:
- CORS:
![cors](https://user-images.githubusercontent.com/25773492/171101923-0116b17c-c19e-438d-9340-f92515240083.png)
- CSRF:
![csrf](https://user-images.githubusercontent.com/25773492/171101936-690710e6-93e3-4ab6-8193-43b20be992a6.png)
- Cookies
![cookies](https://user-images.githubusercontent.com/25773492/171101947-06c4a611-bcdf-4cab-803e-e8bdefd1127b.png)
We updated Viya to 2022.1.1 and the problem with redirects is gone with the latest version of VA SDK.
As far as I know, SAS also provided a patch for 2021.2.5 related to this issue a few days ago.
Now the web app (with the latest VA SDK and Viya 2022.1.1) struggles to get user token:
- Console:
![console](https://user-images.githubusercontent.com/25773492/171109498-b70cb86c-9ee0-4220-b7a2-830fa2472b56.png)
- Network
![network](https://user-images.githubusercontent.com/25773492/171109541-2262c3f7-5858-4f98-9389-ef547db5ce3f.png)

**Comment by YuryShkoda** [comment]
I also tried to use `authenticationType="credentials"` and when log in as a guest I also got 401 from GET request to `/SASLogon/oauth/authorize?client_id=sas.identities&redirect_uri=/identities/&response_type=code&state=25x17-`. The same happens if I log in with my credentials with or without admin permissions.

**Comment by YuryShkoda** [comment]
@ckedwards , you was right suspecting cookies samesite option. Regardless configuration it is still equal to `Lax` not `None`. The configuration has been set before Viya upgrade, so the restart already happened.

**Comment by ckedwards** [comment]
With your upgrade to 2022.1.1, it is possible that you need to make this update to your deployment.

https://go.documentation.sas.com/doc/en/itopscdc/v_028/dplynotes/p1co6ti4lkiy2rn1elzwf9oa0s3p.htm#n0rkuyuckna3djn1lou9zkqrl0o1

**Comment by brmorr** [comment]
@YuryShkoda , the assumption is that the steps in that deployment note will fix the samesite setting on the sas-ingress-nginx cookie.  If that does not change it to SameSite None, or that change doesn't affect this logon problem, then you should open up a support ticket by emailing [VisualAnalyticsSDKsupport@sas.com](mailto:VisualAnalyticsSDKsupport@sas.com).  This way you can give us the HAR data which should allow us to get to the root cause.

**Comment by YuryShkoda** [comment]
@brmorr , unfortunately fixing samesite setting on the sas-ingress-nginx cookie didn't help. I created a ticket with har file using email provided by you.

**Comment by brmorr** [comment]
@YuryShkoda thank you for opening a support ticket and including the HAR.  We have gotten to the root cause of the issue and have the right folks working on a fix.  The fix is on the services side and will come out as a patch on 2022.1.1.  Any followup should happen on the support ticket, so closing this issue.

**Comment by YuryShkoda** [comment]
Hi @brmorr ,

thank you for the update!
